version: '3'

volumes:
    db-v:
        driver: local
        driver_opts:
            device: /home/gkwon/Desktop/inception/srcs/gkwon/data/mariadb
            type: 'none'
            o: 'bind'

    www-v:
        driver: local
        driver_opts:
            device: /home/gkwon/Desktop/inception/srcs/gkwon/data/wordpress
            type: 'none'
            o: 'bind'

services:
    mariadb:
        init: true
        container_name: mariadb
        env_file: .env
        build: ./requirements/mariadb
        restart: always
        networks:
            - intra
        volumes:
            - db-v:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    wordpress:
        container_name: wordpress
        env_file: .env
        build: ./requirements/wordpress
        restart: always
        volumes:
            - www-v:/var/www
        networks:
            - intra
        depends_on:
            mariadb:
                condition: service_healthy

    nginx:
        container_name: nginx
        env_file: .env
        build: ./requirements/nginx
        restart: always
        ports:
            - '443:443'
        volumes:
            - www-v:/var/www
        networks:
            - intra
        depends_on:
            - wordpress
            
networks:
    intra:
        driver: bridge