version: '3'

services:
  mariadb:
    container_name: mariadba
    networks:
      - inception
    #init: true
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - ./tmp_db:/var/lib/mysql
    restart: always
    expose:
      - "3306"

volumes:
  mariadb:
    driver: local

networks:
  inception:
    driver: bridge
