version: '3'

services:
  mariadb:
    init: true
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file:
      - .env
    restart: always
    expose:
      - "3306"
    #volumes:
    #  - ./srcs/gkwon/data/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    init: true
    image: mariadb:gkwon
    container_name: mariadb
    env_file:
      - .env
    #volumes:
    #  - ./gkwon/data/mariadb:/var/lib/mysql
    build: ./requirements/mariadb
    networks:
      - inception
        #ipv4_address: 172.31.0.10
    expose:
      - "3306"
    tty: true
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: wordpress:gkwon
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    #volumes:
    #  - ./srcs/gkwon/data/wordpress:/var/www/html
    build: ./requirements/wordpress
    ports:
      - "9000"
    networks:
      - inception
    tty: true
    restart: always
    init: true

  nginx:
    image: nginx:gkwon
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    #volumes:
    #  - ./srcs/gkwon/data/wordpress:/var/www/html
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    tty: true
    restart: always
    init: true

networks:
  inception:
    driver: bridge
    #ipam:
    #  driver: default
    #  config:
    #    - subnet: 172.31.0.0/16

#volumes:
#  mariadb-volume:
#    name: mariadb-volume
#    driver: local
#    driver_opts:
#      type: none
#      device: ./srcs/gkwon/data/mariadb
#      o: bind

#  wordpress-volume:
#    name: wordpress-volume
#    driver: local
#    driver_opts:
#      type: none
#      device: ./srcs/gkwon/data/wordpress
#      o: bind